const transactions = [
  {
    date: "Nov 30",
    toFrom: "Transfer to Ops / Payroll",
    amount: "-54,810.16",
    account: "AR",
    paymentMethod: "Transfer",
    attachment: true,
  },
  {
    date: "Nov 30",
    toFrom: "Transfer from AR",
    amount: "54,810.16",
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    attachment: true,
  },
  {
    date: "Nov 30",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 30",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 30",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 30",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
  {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
   {
    date: "Nov 28",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
    {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
      {
    date: "Nov 27",
    toFrom: "Lily's Eatery",
    amount: "0.93",
    account: "Ops / Payroll",
    paymentMethod: "Jane B. ••1234",
    attachment: true,
  },
];

export default transactions